# Generated by Django 5.0.3 on 2024-03-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(default='none', max_length=20)),
                ('file', models.CharField(max_length=255)),
                ('cid', models.IntegerField()),
            ],
        ),
    ]
