# Generated by Django 5.0.4 on 2024-06-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentCourses',
            new_name='Lession',
        ),
    ]
