# Generated by Django 5.0.3 on 2024-03-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcourses',
            options={'verbose_name': 'Контент курса', 'verbose_name_plural': 'Контент курсов'},
        ),
    ]
