# Generated by Django 5.0.3 on 2024-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_contentcourses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcourses',
            name='cid',
            field=models.IntegerField(verbose_name='CID курса'),
        ),
        migrations.AlterField(
            model_name='contentcourses',
            name='file',
            field=models.CharField(max_length=255, verbose_name='Файл контента'),
        ),
        migrations.AlterField(
            model_name='contentcourses',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название контента'),
        ),
        migrations.AlterField(
            model_name='contentcourses',
            name='short_name',
            field=models.CharField(default='none', max_length=20, verbose_name='Сокращенное название контента'),
        ),
    ]
