# Generated by Django 5.0.4 on 2024-06-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_rename_contentcourses_lession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lession',
        ),
    ]
