# Generated by Django 5.0.6 on 2024-06-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_delete_lession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='course',
        ),
    ]
