# Generated by Django 5.0.6 on 2024-06-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_remove_homework_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(default='Замечательная работа!', null=True, verbose_name='Коментарий к дз'),
        ),
    ]
