# Generated by Django 5.0.4 on 2024-06-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('main', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursesList',
            new_name='Course',
        ),
    ]
