# Generated by Django 5.0.6 on 2024-06-27 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_homeworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourses',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Курс'),
        ),
    ]
