# Generated by Django 5.0.4 on 2024-06-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('body', models.TextField(default='Текст комментария', unique=True, verbose_name='Текст комментария')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
                ('active', models.BooleanField(default=False, verbose_name='Публикация комментария')),
            ],
            options={
                'verbose_name': 'коментарий',
                'verbose_name_plural': 'коментарии',
                'ordering': ['created_on'],
            },
        ),
    ]
