# Generated by Django 5.0.4 on 2024-06-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
    ]
