# Generated by Django 5.0.4 on 2024-06-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_language_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
