# Generated by Django 5.0.4 on 2024-06-08 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('number_card', models.CharField(max_length=255, verbose_name='Номер карты')),
                ('cvv_card', models.CharField(max_length=255, verbose_name='CVV')),
                ('name_card', models.CharField(max_length=255, verbose_name='Имя владельца карты')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('tg_nick', models.CharField(max_length=255, verbose_name='Ник в телеграм')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Пользователь не переведён на курс')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courseslist', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
            },
        ),
    ]
