# Generated by Django 5.0.4 on 2024-06-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lession',
            name='cid',
        ),
    ]
