# Generated by Django 5.0.4 on 2024-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessions', '0002_remove_lession_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lession',
            name='cid',
            field=models.IntegerField(default=0, help_text='значение устанавливает порядок в списке', verbose_name='CID курса'),
        ),
        migrations.AddField(
            model_name='theme',
            name='cid',
            field=models.IntegerField(default=0, help_text='значение устанавливает порядок в списке', verbose_name='CID курса'),
        ),
    ]
