# Generated by Django 5.0.4 on 2024-06-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessions', '0003_lession_cid_theme_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='short_name',
            field=models.CharField(default='none', max_length=20, verbose_name='Сокращенное название темы'),
        ),
    ]
