# Generated by Django 5.0.6 on 2024-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessions', '0004_theme_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/img/themes/%Y/%m/%d', verbose_name='Изображение темы'),
        ),
    ]
